### ISSUE TITLE
Unit tests and continuous integration

### ISSUE THREAD

**Issue by dacb** [crystalmaths/crystalmaths#5]
Make sure you have a full complement of unit tests and are using continuous integration. You can use the template from the repository I demoed: https://github.com/dacb/codebase_conda

Make sure to put badges in your README.md in the repo root.

I see you do have a `.travis.yml` but it doesn't look like you have unit tests or all the pieces are not tied together.  If you do name your environment file `crystalmaths.yml` you will need to edit the template `.travis.yml`.  Most teams call the environment file `environment.yml`

**Comment by AmyStegmann** [comment]
our environment file has been renamed to environments.yml
