### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by dacb** [crystalmaths/crystalmaths#6]
I notice in the module directory, you don't have a `__init__.py` and there are jupyter notebooks.  If the notebooks are part of the demo, they probably belong in a different directory.  Also, you will need a `test` directory in the module directory with your unit tests.

Make sure you follow the repository layout pattern in this PDF: https://github.com/UWDIRECT/UWDIRECT.github.io/raw/master/Wi20_content/SEDS/L9.Project_Structure.pdf

**Comment by AmyStegmann** [comment]
we are still in development of these items and they will be moved into .py files in this folder
